### ISSUE TITLE
There wasn't any error log when bosh failed to stop system-metrics-agent

### ISSUE THREAD

**Issue by ahrtr** [cloudfoundry/system-metrics-release#2]
From the log of /var/vcap/monit/monit.log, we can tell that BOSH failed to stop system-metrics-agent somehow. Please see the following screen shot,
<img width="917" alt="monit" src="https://user-images.githubusercontent.com/30739825/91868644-8eefdf80-eca7-11ea-8505-309e6d5123d5.png">

But I do not see any error logs in /var/vcap/sys/log/system-metrics-agent/*, please see the following screen shot,
<img width="1226" alt="Screen Shot 2020-09-01 at 9 32 47 PM" src="https://user-images.githubusercontent.com/30739825/91868888-d0808a80-eca7-11ea-8089-ffa8280d6a8d.png">

It seems that system-metrics-agent only pipes the logs to log files during start and not during stop, 
https://github.com/cloudfoundry/system-metrics-release/blob/v2.0.11/jobs/loggr-system-metrics-agent/templates/ctl.erb#L26-L27

**Comment by angelachin** [comment]
Hi @ahrtr,

We've [updated the ctrl script](https://github.com/cloudfoundry/system-metrics-release/commit/d7484e08c90410605616e5c5fca4a3bcde2c9c77) to output logging on a monit stop. We believe this addresses your issue and are closing the issue accordingly-- feel free to re-open if you have any questions/concerns.

This fix should be in the next release, which we are [tracking with the following story](https://www.pivotaltracker.com/story/show/175465374).

Thanks,
Angela and @dtimm
